spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
              - DELETE
      routes:
        - id: directory-service-folder-endpoint
          uri: lb://DIRECTORY-SERVICE/
          predicates:
            - Path=/folder/**
        - id: directory-service-file-endpoint
          uri: lb://DIRECTORY-SERVICE/
          predicates:
            - Path=/file/**
  application:
    name: gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: false
  instance:
    prefer-ip-address: true
