spring:
  cloud:
    gateway:
      routes:
        - id: folder-previous-folders
          uri: lb://STORAGE-DATABASE-SERVICE/
          predicates:
            - Path=/folder/previous/folders/**
        - id: folder-download
          uri: lb://STORAGE-SERVICE/
          predicates:
            - Path=/folder/download
        - id: file-download
          uri: lb://STORAGE-SERVICE/
          predicates:
            - Path=/file/download
        - id: directory-service-folder-endpoint
          uri: lb://DIRECTORY-SERVICE/
          predicates:
            - Path=/folder/**
        - id: directory-service-file-endpoint
          uri: lb://DIRECTORY-SERVICE/
          predicates:
            - Path=/file/**
  application:
    name: gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: false
  instance:
    prefer-ip-address: true
